# Generated by Django 5.2.8 on 2025-11-15 07:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_election_candidate_election'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
